services:
  postgres:
    image: postgres:16
    container_name: postgres-local
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
 

  api:
    build:
      context: ./obras-api
      dockerfile: Dockerfile
    container_name: obras-api
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    env_file:
      - obras-api/.env.prod

volumes:
  postgres_data:
